/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exam2;

import org.junit.jupiter.api.Test;

class AppTest {
  @Test void appHasAGreeting() {
    // TODO: add unit tests
  }
}
