/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package exam2;

import org.junit.jupiter.api.Test;

class FileSystemTest {
  @Test void loadFromFile() {
    FileSystem sys = new FileSystem();
    sys.loadFolderItemFromFile("../folderItem.dat");
    sys.displayFolderItemInfo();
  }
}
